### ISSUE TITLE
Need full path to Kickstart files when using Docker container

### ISSUE THREAD

**Issue by kwadroke** [AlmaLinux/sig-livemedia#14]
Attempting to build without full path to kickstart files will result in a error.

When ran from /:
```
Failed to parse kickstart file 'almalinux-8-live-xfce.ks' : The following problem occurred on line 0 of the kickstart file:

Unable to open input kickstart file: Error opening file: [Errno 2] No such file or directory: 'almalinux-8-live-xfce.ks'
```

When ran from /code:  
```
Error creating Live CD : Failed to loopback mount '/var/tmp/imgcreate-0vrhvl5m/tmp-o39v6d0d/ext3fs.img' : Failed to allocate loop device for '/var/tmp/imgcreate-0vrhvl5m/tmp-o39v6d0d/ext3fs.img'
```

Will need to be changed for all 4 Docker examples.

Current (XFCE):  
```
ksflatten --config almalinux-8-live-xfce.ks --output flat-xfce.ks
livecd-creator --config flat-xfce.ks \
               --fslabel AlmaLinux-8-LiveDVD-XFCE \
               --title=AlmaLinux-8-LiveDVD \
               --product="AlmaLinux 8 Live" \
               --cache=/code/pkg-cache-alma \
               --releasever=8
```

Should be (XFCE):  
```
ksflatten --config /code/almalinux-8-live-xfce.ks --output flat-xfce.ks
livecd-creator --config flat-xfce.ks \
               --fslabel AlmaLinux-8-LiveDVD-XFCE \
               --title=AlmaLinux-8-LiveDVD \
               --product="AlmaLinux 8 Live" \
               --cache=/code/pkg-cache-alma \
               --releasever=8
```  
Will remove /flat-xfce.ks if container is shutdown and will need to be regenerated on next run.

This will also work (XFCE):  
```
ksflatten --config /code/almalinux-8-live-xfce.ks --output /code/flat-xfce.ks
livecd-creator --config /code/flat-xfce.ks \
               --fslabel AlmaLinux-8-LiveDVD-XFCE \
               --title=AlmaLinux-8-LiveDVD \
               --product="AlmaLinux 8 Live" \
               --cache=/code/pkg-cache-alma \
               --releasever=8
```        
Will keep flat-xfce.ks after container is shutdown (file in /code volume)

Tested on Fedora 34 using Docker

**Comment by srbala** [comment]
@kwadroke thanks for your testing and input using docker build. `Dockerfile` was missing `WORKDIR` statement, fixed it now. please rebuild the docker image OR do `docker pull almalinux/ks2rootfs:livecd-tools`. Updated image is avaiable in `dockerhub` now.

**Comment by srbala** [comment]
Now docker shell should directly take it `code` folder. Keeping `code` as current working directory is important since resulting `ISO` file will be in the same folder which is mapped host current working directory.

**Comment by srbala** [comment]
After your verification and no more issue, please close this issue. Thanks again for you testing/verification

**Comment by srbala** [comment]
KS files were updated in my last commit, please pull latest versions prior to your testing, thank you

**Comment by kwadroke** [comment]
Thank you. The `WORKDIR` entry fixed it. I rebuilt the container and it created the ISO in /code.

The latest commit also fixed the wallpaper in XFCE, which was going to be next on my list.

**Comment by srbala** [comment]
> Thank you. The `WORKDIR` entry fixed it. I pulled down the latest commit, rebuilt the container and it created the ISO in /code.

Great, Container changes works as expected. @kwadroke What's your host OS (Mac or Windows etc). I know it was working in MacOS.

> The latest commit also fixed the wallpaper in XFCE, which was going to be next on my list.

AlmaLinux `Wallpaper` and `Cache on build` are the pending items prior to official `Beta` release. I think we are ready now 😄.

**Comment by kwadroke** [comment]
> > Thank you. The `WORKDIR` entry fixed it. I pulled down the latest commit, rebuilt the container and it created the ISO in /code.
> 
> Great, Container changes works as expected. @kwadroke What's your host OS (Mac or Windows etc). I know it was working in MacOS.
> 

Linux (Fedora 34)

> > The latest commit also fixed the wallpaper in XFCE, which was going to be next on my list.
> 
> AlmaLinux `Wallpaper` and `Cache on build` are the pending items prior to official `Beta` release. I think we are ready now smile.

:)
