### ISSUE TITLE
Link to the Live Media SIG on the AlmaLinux Wiki?

### ISSUE THREAD

**Issue by kwadroke** [AlmaLinux/sig-livemedia#15]
Put a link on this repo to cross advertise the Live Media SIG's Wiki Page for more information on the SIG itself, as well as chat room info.
https://wiki.almalinux.org/sigs/LiveMedia.html

**Comment by srbala** [comment]
@ezamriy Please add project repo URL in channel header

**Comment by srbala** [comment]
Project readme file udpated and created wiki PR https://github.com/AlmaLinux/wiki/pull/50 to solve

**Comment by srbala** [comment]
@kwadroke channel admin @ezamriy adding the links https://chat.almalinux.org/almalinux/pl/7mxumxrsn78afeztp55corg4rw

**Comment by srbala** [comment]
links updated
