### ISSUE TITLE
Almalinux 9.0 xfce live-image not installing packages?

### ISSUE THREAD

**Issue by pinckpockett** [AlmaLinux/sig-livemedia#24]
When I try to install anything  while using the live usb as a live system user. I try using the dnf package manager and it says:

warning: Found bdb_ro Packages database while attempting sqlite

Then Error: Unable to Fina a match: package*

I am bringing this to light in case anyone uses the 9.0 xfce live image.

I Haven't tested the other live images so IFK if this is a problem for all of them.

**Comment by srbala** [comment]
@pinckpockett issue a `sudo rpm --rebuilddb`, you should be able to make install packages after it.

**Comment by pinckpockett** [comment]
> @pinckpockett issue a `sudo rpm --rebuilddb`, you should be able to make install packages after it.

Okay, thanks for the reply.

**Comment by pinckpockett** [comment]
Forgot to mention, does something like this warrent a fix on the main branch or is usually an error on the individual's computer?

I ask for anyone who wants to use the live usb and runs into a problem like this.

**Comment by srbala** [comment]
Working doing some script updates after that, public ISO's will be updated

**Comment by pinckpockett** [comment]
> Working doing some script updates after that, public ISO's will be updated

Okay, thank you for updating me on this. I hope the issue is fixed soon.
