### ISSUE TITLE
Missing directories in XFCE live iso

### ISSUE THREAD

**Issue by sboldyreva** [AlmaLinux/sig-livemedia#30]
XFCE Live Media iso has no other user directories but the desktop one. This issue presents before and after installation. 

![image](https://github.com/AlmaLinux/sig-livemedia/assets/87830789/34c72dc9-a2ee-41e4-869c-33354923e11f)

**Comment by andrewlukoshko** [comment]
These packages are missing:
xdg-user-dirs-gtk
xdg-utils

**Comment by sboldyreva** [comment]
fixed
