### ISSUE TITLE
MATE: Installation crashes on openvpn package

### ISSUE THREAD

**Issue by LKHN** [AlmaLinux/sig-livemedia#44]
Both major versions of AlmaLinux OS are affected.

See: https://bugzilla.redhat.com/show_bug.cgi?id=2239722

**Comment by LKHN** [comment]
EPEL9: https://src.fedoraproject.org/rpms/openvpn/pull-request/3
EPEL8: https://src.fedoraproject.org/rpms/openvpn/pull-request/4

**Comment by andrewlukoshko** [comment]
We dropped openvpn packages from Live Media for now

**Comment by andrewlukoshko** [comment]
Fixed by https://github.com/AlmaLinux/sig-livemedia/pull/69
